import React from 'react';
import './NodeDetailsPopup.css';

const NodeDetailsPopup = ({ node, onClose }) => {
  if (!node) return null;

  const description = node.description || 'No description available';
  const source = node.source || 'Generated by AI';

  return (
    <div className="node-tooltip">
      <button className="tooltip-close" onClick={onClose}>×</button>
      <div className="tooltip-content">
        <p className="tooltip-description">{description}</p>
        <div className="tooltip-source">
          <span className="source-label">Source:</span>
          <span className="source-value">{source}</span>
        </div>
      </div>
    </div>
  );
};

export default NodeDetailsPopup;
