import React, { useEffect, useRef, useState } from 'react';
import './NodeDetailsPopup.css';

const NodeDetailsPopup = ({ node, nodeRef, onClose }) => {
  const popupRef = useRef(null);
  const [position, setPosition] = useState({ top: 0, left: 0 });

  // Update position function
  const updatePosition = () => {
    if (nodeRef && nodeRef.current) {
      const rect = nodeRef.current.getBoundingClientRect();
      setPosition({
        top: rect.bottom + 8, // 8px below the node
        left: rect.left + rect.width / 2 // centered horizontally
      });
    }
  };

  // Initial position and continuous updates
  useEffect(() => {
    updatePosition();

    // Update position on scroll, resize, or any transformation
    const handleUpdate = () => {
      updatePosition();
    };

    // Listen to various events that might change node position
    window.addEventListener('scroll', handleUpdate, true);
    window.addEventListener('resize', handleUpdate);

    // Use requestAnimationFrame for smooth updates during pan/zoom
    let rafId;
    const rafUpdate = () => {
      handleUpdate();
      rafId = requestAnimationFrame(rafUpdate);
    };
    rafId = requestAnimationFrame(rafUpdate);

    return () => {
      window.removeEventListener('scroll', handleUpdate, true);
      window.removeEventListener('resize', handleUpdate);
      if (rafId) cancelAnimationFrame(rafId);
    };
  }, [nodeRef]);

  useEffect(() => {
    const handleClickOutside = (event) => {
      if (popupRef.current && !popupRef.current.contains(event.target)) {
        onClose();
      }
    };

    // Add event listener with slight delay to avoid immediate close
    setTimeout(() => {
      document.addEventListener('mousedown', handleClickOutside);
    }, 0);

    return () => {
      document.removeEventListener('mousedown', handleClickOutside);
    };
  }, [onClose]);

  if (!node) return null;

  const description = node.description || 'No description available';
  const source = node.source || 'Generated by AI';

  return (
    <div
      ref={popupRef}
      className="node-tooltip"
      style={{
        position: 'fixed',
        top: `${position.top}px`,
        left: `${position.left}px`
      }}
    >
      <button className="tooltip-close" onClick={onClose}>×</button>
      <div className="tooltip-content">
        <p className="tooltip-description">{description}</p>
        <div className="tooltip-source">
          <span className="source-label">Source:</span>
          <span className="source-value">{source}</span>
        </div>
      </div>
    </div>
  );
};

export default NodeDetailsPopup;
